Models/CreateItemTodo.cs
namespace ConsumeAPI.Models
{
    public class CreateItemTodo
    {
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace ConsumeAPI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ItemTodo.cs
namespace ConsumeAPI.Models
{
    public class ItemTodo
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

Models/LoginItemTodo.cs
using System.ComponentModel.DataAnnotations;

namespace ConsumeAPI.Models
{
    public class LoginItemTodo
    {
        [Key]
        public string Username { get; set; } = null!;
        public string Password { get; set; } = null!;
        public bool IsLoggedIn { get; set; }
    }
}

Models/UpdateItemTodo.cs
namespace ConsumeAPI.Models
{
    public class UpdateItemTodo
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

Controllers/ItemController.cs
using ConsumeAPI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ConsumeAPI.Controllers
{
    public class ItemController : Controller
    {
        string baseURL = "http://localhost:5000/todos/";

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateItemTodo newItem)
        {
            using (var client = new HttpClient())
            {
                HttpResponseMessage response = await client.PostAsJsonAsync(baseURL, newItem);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Read", "Item");
                }
                else
                {
                    Console.WriteLine("Error calling API.");
                }
            }
            return RedirectToAction("Read", "Item");
        }

        [HttpGet]
        public async Task<IActionResult> Read()
        {
            IList<ItemTodo> todoList = new List<ItemTodo>();

            using (var client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync(baseURL);
                if (response.IsSuccessStatusCode)
                {
                    string dataResult = response.Content.ReadAsStringAsync().Result;
                    todoList = JsonConvert.DeserializeObject<IList<ItemTodo>>(dataResult);
                }
                else
                {
                    Console.WriteLine("Error calling API.");
                }
                ViewData.Model = todoList;
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Details([FromRoute] Guid id)
        {
            ItemTodo todoItem = new ItemTodo();

            using (var client = new HttpClient())
            {
                HttpResponseMessage getData = await client.GetAsync(baseURL+$"get?id={id}");
                if (getData.IsSuccessStatusCode)
                {
                    string dataResult = getData.Content.ReadAsStringAsync().Result;
                    todoItem = JsonConvert.DeserializeObject<ItemTodo>(dataResult);
                }
                else
                {
                    Console.WriteLine("Error calling API.");
                }
                ViewData.Model = todoItem;
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Update([FromRoute] Guid id)
        {
            UpdateItemTodo updateItem = new();
            using (var client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync(baseURL+$"get?id={id}");

                if (response.IsSuccessStatusCode)
                {
                    string dataResult = response.Content.ReadAsStringAsync().Result;
                    var item = JsonConvert.DeserializeObject<ItemTodo>(dataResult);
                    updateItem = new UpdateItemTodo()
                    {
                        Title = item.Title,
                        Description = item.Description 
                    };
                }
                else
                {
                    Console.WriteLine("Error calling API.");
                }
            }
            return View(updateItem);
        }
        [HttpPost]
        public async Task<IActionResult> Update(UpdateItemTodo updateItem)
        {
            using (var client = new HttpClient())
            {
                HttpResponseMessage response = await client.PutAsJsonAsync(baseURL+$"put?id={updateItem.Id}", updateItem);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Read", "Item");
                }
                else
                {
                    Console.WriteLine("Error calling API.");
                }
            }
            return RedirectToAction("Read", "Item");
        }

        [HttpGet]
        public async Task<IActionResult> Delete([FromRoute] Guid id)
        {
            using (var client = new HttpClient())
            {
                HttpResponseMessage getData = await client.DeleteAsync(baseURL + $"delete?id={id}");
                if (getData.IsSuccessStatusCode)
                {
                    return RedirectToAction("Read", "Item");
                }
                else
                {
                    Console.WriteLine("Error calling API.");
                }
            }
            return RedirectToAction("Read", "Item");
        }
    }
}

Controllers/LoginTodoController.cs
using Microsoft.AspNetCore.Mvc;
using ConsumeAPI.Models;
using System.Security.Claims;

namespace ConsumeAPI.Controllers
{
    public class LoginTodoController : Controller
    {
        string baseURL = "http://localhost:5000/";

        [HttpGet]
        public IActionResult Login()
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            if (claimUser.Identity.IsAuthenticated)
            {
                return RedirectToAction("Read", "Item");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginItemTodo loginModel)
        {
            if (loginModel.Username != null && loginModel.Password != null)
            {
                using (var client = new HttpClient())
                {
                    HttpResponseMessage getData = await client.PostAsJsonAsync(baseURL + "Login", loginModel);
                    if (getData.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Read", "Item");
                    }
                    else
                    {
                        Console.WriteLine("Error calling API.");
                    }
                }
            }
            ViewData["ValidateMessage"] = "User Not Found";
            return View();
        }
    }
}

Views/Item/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ConsumeAPI.Models.ItemTodo

<div class="container w-50 mt-5">
    <h1>Add New Todo</h1>
    <form action="Create" method="post">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Title</label>
            <input type="text" class="form-control" asp-for="Title">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Description</label>
            <textarea class="form-control" asp-for="Description"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Views/Item/Details.cshtml
@model ConsumeAPI.Models.ItemTodo
@{
    ViewData["title"] = "Details | Todo";
}
<div>
    <h1>Task Details</h1>
    <table class="table">
        <thead>
            <tr>
                <th>S.N.</th>
                <th>ID</th>
                <th>Title</th>
                <th>Description</th>
                <th colspan="3">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>@Model.Id</td>
                <td>@Model.Title</td>
                <td>@Model.Description</td>
                <td>
                    <a asp-action="Update" asp-route-id="@Model.Id">
                        Update
                    </a>
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@Model.Id">
                        Delete
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
    <a asp-action="Read">
        Go Back
    </a>
</div>

Views/Item/Read.cshtml
@model IEnumerable<ItemTodo>
@{
    ViewData["title"] = "View | Todo";
}
<div class="container w-50">
    <h1>Tasks in Todo List</h1>
    <a asp-action="Create"><h3> Add Task </h3></a>
    <table class="table">
        <thead>
            <tr>
                <th>S.N.</th>
                <th>Title</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 1;
            }
            @foreach (var item in Model)
            {
                <tr>
                    <td>@i</td>
                    <td>@item.Title</td>
                    <td><a asp-action="Details" asp-route-id="@item.Id">Details</a></td>
                </tr>
                i++;
            }
        </tbody>
    </table>
</div>

Views/Item/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ConsumeAPI.Models.UpdateItemTodo

<div class="container w-50 mt-5">
    <h1>Update Todo</h1>
    <form asp-action="Update" method="post">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Title</label>
            <input type="text" class="form-control" asp-for="Title">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Description</label>
            <textarea class="form-control" asp-for="Description"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/LoginTodo/Login.cshtml
@model ConsumeAPI.Models.LoginItemTodo
@{
}
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div class="container mt-5 w-25">
        <h1 class="my-3">User Login</h1>
        <form asp-controller="LoginTodo" asp-action="Login" method="post">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Username</label>
                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" asp-for="Username">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" asp-for="Password">
            </div>
            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1" asp-for="IsLoggedIn">
                <label class="form-check-label" for="exampleCheck1">Stay Logged In</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        @if (ViewData["ValidateMessage"] != null)
        {
            <br />
            <br />
            <label>
                @ViewData["ValidateMessage"]
            </label>
        }
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home - Todo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Todo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Item" asp-action="Read">Todo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Read">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Read">View Todo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Create">Add Todo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="LogOut">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>